POST http://localhost:5237/Profile/UpdateProfile
Content-Type: application/x-www-form-urlencoded
Cookie: .AspNetCore.Identity.Application=CfDJ8BvamOWVNq5LrcchiCuJ9IUuLUfnSl5NN60hO5nn-NEmcxyAO3zoh5e59DArGHVVM_R4YqpdpjNUOFByFogMq54LIRCQptN8qmjTBzyBgQ9wol47eDF6jSefLPoyJu7PLGYz7jfn8872SuuOxvr7b2XlHplJG3VkYUCCJxHXeEino1fuoc_FhJxqMl0ILwhTxGwOfNyZ9MFcvGWHFWOTMMBDyNtQOXmm57ogYlFsdlVWB_W62yJBXNc-yxzfl-NIRVQTqzX-vgfS6Aua3yXFqbINXBbw8Yymde6MJNjFuIJCH5Ds62eDxyq7vuXbqvjErun_EQ86BQHPj1VfYHBStXWj8c9Ajv2agu_xSXqkFjjqpoo4kRtPNuKsZFtqgilGc92HdYVyOESiJ5LcXmExh5O04IApEZvo7yvNRh4nPmLi-Ese-GIo0rkr9-Bc6lEqRzZfVtA0Oq7hkSLfGa84F80MylLisJZg0Ssk6sV5sM970R73keBHZNUMI_GOfLSUJMw7c2huJa8osVxkKuJnqWnu9xr1axc4BuSykv33Yp2FmyYJl9Rsy5TCcheOnzYfAXyTmjjcLSmnM049_LWSCdb34HUXZM3rIOi5Fw9oOLZb4CIRU9unmt_YFdUoNm1WXg03R0BS9jyjUFNCJYPWUZaL6sj4cgg1rJwhgkljpXHdVuDFWWV9U8P7LD1KCAQI2DWcCb1r_zPRe6c_3IeKmCQawiApHjSbvITLJhwdosLhwh13ekkLDOhv9Wh5eL9yPQ

Name=New Name Here&Email=newuser@example.com&DateOfBirth=1990-01-15